In [25]:
import tensorflow as tf

In [26]:
#Create a Constant tensor A
A=tf.constant([[4,3],[6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [27]:
# Create a Variable tensor V
V=tf.Variable([[3,1],[5,2]])
V

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>

In [29]:
# Concatenate Columns column wise
AV_concatenated=tf.concat(values=[A,V],axis=1)
AV_concatenated


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 3, 1],
       [6, 1, 5, 2]], dtype=int32)>

In [30]:
# Concatenate Columns row wise
AV_concatenated=tf.concat(values=[A,V],axis=0)
AV_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [3, 1],
       [5, 2]], dtype=int32)>

In [31]:
tensor=tf.zeros(shape=[3,4],dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [ ]:
tensor=tf.ones(shape=[3,4],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
reshaped_tensor=tf.reshape(tensor=tensor,shape=[4,3])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tensor=tf.random.uniform(shape=[3,4],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.34669507, 0.7219908 , 0.3727566 , 0.82596684],
       [0.82848096, 0.7586385 , 0.95422435, 0.92092764],
       [0.16300368, 0.9737185 , 0.2967763 , 0.05527353]], dtype=float32)>

In [ ]:
reshaped_tensor=tf.reshape(tensor=tensor,shape=[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.34669507, 0.7219908 , 0.3727566 ],
       [0.82596684, 0.82848096, 0.7586385 ],
       [0.95422435, 0.92092764, 0.16300368],
       [0.9737185 , 0.2967763 , 0.05527353]], dtype=float32)>

In [ ]:
tesnor=tf.constant([[4.6,4.2],
                   [7.5,3.6],
                   [2.7,9.4],
                   [6.7,8.9]],
                   dtype=tf.float32)

In [ ]:
#Typecasting a tensor
tesnor_as_int=tf.cast(tesnor,tf.int32)
print(tesnor)
print(tesnor_as_int)

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.9]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32)


In [ ]:
a=tf.transpose(tesnor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]], dtype=int32)>

In [ ]:
# Matrix multiplication of tensors

A=tf.constant([[5,8],[3,9]])

#Some vector v

v=tf.constant([[4],[2]])

Av=tf.matmul(A,v)
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]], dtype=int32)>

In [ ]:
#Element wise multiplication
Av=tf.multiply(A,v)
Av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]], dtype=int32)>

In [ ]:
#creating identity matrix

A=tf.constant([[4,9],
               [5,6],
               [1,8]])

rows,columns=A.shape
print('rows:',rows,'columns:',columns)

#making identity matrix
A_identity=tf.eye(num_rows=rows,num_columns=columns,dtype=tf.int32)
A_identity

rows: 3 columns: 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]], dtype=int32)>

In [2]:
import datetime,warnings,scipy
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
plt.rcParams["patch.force_edgecolor"]=True
plt.style.use('fivethirtyeight')
mpl.rc('patch',edgecolor='dimgray',linewidth=1)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity ='last_expr'
pd.options.display.max_columns=50
%matplotlib inline
warnings.filterwarnings('ignore')

In [3]:
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.metrics import mean_squared_error

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
df=pd.read_csv('/content/air_quality.csv',sep=' ')
df.head(3)

No  Profile     Tanggal       Jam     O3    CO    NO2    SO2      NO  \
0   1  BANDUNG  2019-05-19  00:04:19  21.35  0.78   6.77  14.06  26.168   
1   2  BANDUNG  2019-05-19  00:15:01   5.93  0.82  14.87  17.23  53.853   
2   3  BANDUNG  2019-05-19  00:30:06   6.62  0.63  22.24   2.31  38.304   

      CO2      VOC  PM1  PM2.5  PM4   PM10  TSP  TEMP    HUM   WS  WD  ISPU  \
0  409.86  251.202  0.0    0.0  0.0   2.77  0.0  21.4  100.0  0.6   5     9   
1  394.79  501.356  0.0    0.0  0.0  11.95  0.0  42.6  200.0  0.0   2    12   
2  390.66  753.291  0.0    0.0  0.0  12.71  0.0  63.6  299.2  0.0   2    13   

  Status  Unnamed: 22  
0   BAIK          NaN  
1   BAIK          NaN  
2   BAIK          NaN

In [8]:
#Convert Time to datetime format

def combine_date(df,tab_name):
  list_tab=[]
  for i in range(df.shape[0]):
    list_tab.append(df.loc[i,'Tanggal']+'T'+df.loc[i,tab_name][0:2])
  return np.array(list_tab,dtype='datetime64')

#Convert Time to datetime format:
df['Datetime']=combine_date(df,'Jam')


def combine_date(df,tab_name):
  list_tab=[]
  for i in range(df.shape[0]):
    list_tab.append(df.loc[i,'Tanggal']+'T'+df.loc[i,tab_name][0:2])
  return np.array(list_tab,dtype='datetime64')

#Convert Time to datetime format:
df['Datetime']=combine_date(df,'Jam')

df.head()

No  Profile     Tanggal       Jam     O3    CO    NO2    SO2      NO  \
0   1  BANDUNG  2019-05-19  00:04:19  21.35  0.78   6.77  14.06  26.168   
1   2  BANDUNG  2019-05-19  00:15:01   5.93  0.82  14.87  17.23  53.853   
2   3  BANDUNG  2019-05-19  00:30:06   6.62  0.63  22.24   2.31  38.304   
3   4  BANDUNG  2019-05-19  00:49:19  13.29  0.44  19.00   5.32  18.962   
4   5  BANDUNG  2019-05-19  01:04:19   2.44  0.47  26.74  13.61  35.270   

      CO2      VOC  PM1  PM2.5  PM4   PM10  TSP  TEMP    HUM     WS  WD  ISPU  \
0  409.86  251.202  0.0    0.0  0.0   2.77  0.0  21.4  100.0  0.600   5     9   
1  394.79  501.356  0.0    0.0  0.0  11.95  0.0  42.6  200.0  0.000   2    12   
2  390.66  753.291  0.0    0.0  0.0  12.71  0.0  63.6  299.2  0.000   2    13   
3  401.23  251.043  0.0    0.0  0.0   1.20  0.0  21.3   88.2  0.525   5     6   
4  381.67  250.471  0.0    0.0  0.0   3.52  0.0  21.3   97.4  0.975   5     9   

  Status  Unnamed: 22            Datetime  
0   BAIK          NaN 2019-05-19 00:00:00  
1   BAIK          NaN 2019-05-19 00:00:00  
2   BAIK          NaN 2019-05-19 00:00:00  
3   BAIK          NaN 2019-05-19 00:00:00  
4   BAIK          NaN 2019-05-19 01:00:00

In [9]:
#Convert into hourly data

df=df[['Datetime','O3','CO','NO2','SO2','NO',	'CO2'	,'VOC'	,'PM1',	'PM2.5',	'PM4'	,'PM10',	'TSP'	,'TEMP',	'HUM',	'WS',	'WD',	'ISPU',	'Status','Profile','Tanggal']]

df2=df.groupby(['Datetime']).mean()
df2.head()

O3        CO     NO2      SO2        NO  \
Datetime                                                              
2019-05-19 00:00:00  11.797500  0.667500  15.720   9.7300  34.32175   
2019-05-19 01:00:00   3.816667  0.373333  22.600  20.0900  39.82100   
2019-05-19 02:00:00   6.450000  0.332500  24.130  26.3100  51.29325   
2019-05-19 03:00:00   4.740000  0.180000  25.975  24.3900  43.51850   
2019-05-19 04:00:00  19.692500  0.202500  20.395  18.6225  53.37925   

                            CO2        VOC  PM1  PM2.5  PM4      PM10  TSP  \
Datetime                                                                     
2019-05-19 00:00:00  399.135000  439.22300  0.0    0.0  0.0  7.157500  0.0   
2019-05-19 01:00:00  388.536667  250.39400  0.0    0.0  0.0  3.293333  0.0   
2019-05-19 02:00:00  396.242500  251.04575  0.0    0.0  0.0  6.487500  0.0   
2019-05-19 03:00:00  401.355000  252.24875  0.0    0.0  0.0  4.700000  0.0   
2019-05-19 04:00:00  399.335000  694.23975  0.0    0.0  0.0  5.262500  0.0   

                          TEMP         HUM       WS        WD       ISPU  
Datetime                                                                  
2019-05-19 00:00:00  37.225000  171.850000  0.28125  3.500000  10.000000  
2019-05-19 01:00:00  20.966667   95.033333  0.67500  4.666667  12.666667  
2019-05-19 02:00:00  20.150000   97.500000  0.09375  3.750000  16.250000  
2019-05-19 03:00:00  19.850000  100.000000  0.07500  5.000000  15.000000  
2019-05-19 04:00:00  53.475000  272.500000  0.18750  5.250000  13.250000

In [10]:
#Descriptive statistics of variables

df.describe()

O3           CO          NO2          SO2           NO  \
count  9231.000000  9231.000000  9231.000000  9231.000000  9231.000000   
mean      8.743761     0.223115    16.294503    11.778135    37.358815   
std       7.249940     0.294420     9.980935     6.353669    15.577667   
min       0.050000     0.000000     0.060000     0.050000     0.379000   
25%       3.920000     0.070000    10.910000     7.430000    26.547000   
50%       7.260000     0.160000    15.410000    11.500000    38.683000   
75%      11.440000     0.300000    20.440000    15.420000    47.027000   
max      87.340000    13.970000   443.380000    62.640000   232.100000   

               CO2          VOC          PM1        PM2.5          PM4  \
count  9231.000000  9231.000000  9231.000000  9231.000000  9231.000000   
mean    394.624556   258.735153     0.188874     0.233940     0.275431   
std       8.881109   118.047968     2.458815     3.052461     3.573004   
min     379.000000     0.000000     0.000000     0.000000     0.000000   
25%     386.910000   247.116000     0.000000     0.000000     0.000000   
50%     394.560000   250.830000     0.000000     0.000000     0.000000   
75%     402.340000   253.110000     0.000000     0.000000     0.000000   
max     410.000000  2281.690000    63.900000    81.500000    92.700000   

              PM10          TSP         TEMP          HUM           WS  \
count  9231.000000  9231.000000  9231.000000  9231.000000  9231.000000   
mean      5.969080     0.342021    25.081010    76.911364    26.432101   
std       5.865517     4.382619    11.172151    46.180806    55.228876   
min       0.020000     0.000000     1.900000    25.400000     0.000000   
25%       2.085000     0.000000    20.900000    57.400000     0.000000   
50%       4.420000     0.000000    23.700000    75.600000     1.050000   
75%       8.440000     0.000000    27.900000    91.400000     6.937500   
max     105.300000   108.400000   227.000000   900.000000   216.225000   

                WD         ISPU  
count  9231.000000  9231.000000  
mean      7.074423     9.813021  
std       3.978570     5.444562  
min       0.000000     2.000000  
25%       4.000000     7.000000  
50%       6.000000     9.000000  
75%      11.000000    12.000000  
max      29.000000   157.000000

In [13]:
#Calculate quantile for each variable

def calculate_quantile(i,df2):
  Q1=df2[[i]].quantile(0.25)[0]
  Q3=df2[[i]].quantile(0.75)[0]
  IQR=Q3-Q1
  min=df2[[i]].min()[0]
  max=df2[[i]].max()[0]

  min_IQR=Q1-1.5*IQR
  max_IQR=Q3+1.5*IQR

  return Q1,Q3,min,max,min_IQR,max_IQR

#delete first and last rows to avoid missing value extrapolation
df2.drop(index=[df2.index[0],df2.index[df2.shape[0]-1]],inplace=True)

#find and interpolate the outliers
for i in df2.columns:
  print('\nAttributes-',i,':')
  Q1,Q3,min,max,min_IQR,max_IQR=calculate_quantile(i,df2)
  print('Q1= %.2f' % Q1)
  print('Q3=%2f' % Q3)
  print('min IQR=% 2f'%min_IQR)
  print('max IQR=% 2f' %max_IQR)

  if(min < min_IQR):
    print('---->Low outlier is found=%.2f' % min)
  if(max > max_IQR):
   print('---->High outlier is found=%.2f' % max)

  def convert_nan(x,max_IQR=max_IQR,min_IQR=min_IQR):
    if((x>max_IQR)|(x<min_IQR)):
      x=np.nan
    else:
      x=x
    return x
  def convert_nan_HUM(x,max_IQR=100.0,min_IQR=min_IQR):
    if((x>max_IQR)|(x<min_IQR)):
      x=np.nan
    else:
      x=x
    return x 
  if(i=='HUM'):
    df2[i]=df2[i].map(convert_nan_HUM)
    df2[i]=df2[i].interpolate(method='linear')

  if(i!='HUM'):
    df2[i]=df2[i].map(convert_nan)
    df2[i]=df2[i].interpolate(method='linear')

  if(len(df2[df2[i].isnull()][i])==0):
    print('################# Outliers have been interpolated ##############')



Attributes- O3 :
Q1= 5.88
Q3=10.373333
min IQR=-0.855833
max IQR= 17.110833
---->High outlier is found=33.74
################# Outliers have been interpolated ##############

Attributes- CO :
Q1= 0.08
Q3=0.295833
min IQR=-0.236458
max IQR= 0.615208
---->High outlier is found=13.95
################# Outliers have been interpolated ##############

Attributes- NO2 :
Q1= 13.01
Q3=19.934167
min IQR= 2.623750
max IQR= 30.320417
---->Low outlier is found=2.04
---->High outlier is found=99.60
################# Outliers have been interpolated ##############

Attributes- SO2 :
Q1= 8.99
Q3=14.566667
min IQR= 0.625000
max IQR= 22.931667
---->High outlier is found=46.29

Attributes- NO :
Q1= 28.44
Q3=46.015333
min IQR= 2.085750
max IQR= 72.373083
---->High outlier is found=194.55
################# Outliers have been interpolated ##############

Attributes- CO2 :
Q1= 391.84
Q3=397.419500
min IQR= 383.466583
max IQR= 405.791250
---->Low outlier is found=380.42
---->High outlier is found=408.82
#####

In [15]:
# Log transformations to deal with skewed data

dataset=np.log1p(df2[['TEMP']].values)
dataset.shape

(1731, 1)

In [16]:
#Spli the dataset into train and test sets

train_size=int(len(dataset)*0.75)
test_size=len(dataset)-train_size
train,test=dataset[0:train_size,:],dataset[train_size:len(dataset),:]
print(len(train),len(test))

1298 433


In [18]:
#Convert an array of values into a dataset matrix

def create_dataset(dataset,look_back=1):
  dataX,dataY=[],[]
  for i in range(len(dataset)-look_back-1):
    a=dataset[i:(i+look_back),0]
    dataX.append(a)
    dataY.append(dataset[i+look_back,0])
  return np.array(dataX),np.array(dataY)

# Reshape the train and test data
look_back=1
trainX,trainY=create_dataset(train,look_back)
testX,testY=create_dataset(test,look_back)

print('Shape of trainX :',trainX.shape)
print('Shape of trainY :',trainY.shape)

print('Shape of testX :',testX.shape)

print('Shape of testY :',testY.shape)

Shape of trainX : (1296, 1)
Shape of trainY : (1296,)
Shape of testX : (431, 1)
Shape of testY : (431,)


In [19]:
# Reshape the input array in the form - [samples,time steps, features]

trainX=np.reshape(trainX,(trainX.shape[0],1,trainX.shape[1]))
testX=np.reshape(testX,(testX.shape[0],1,testX.shape[1]))

print('Shape of trainX: ',trainX.shape)
print('Shape of testX: ',testX.shape)

Shape of trainX:  (1296, 1, 1)
Shape of testX:  (431, 1, 1)


In [20]:
# Create and fit the LSTM Neural Network

model=Sequential()
model.add(LSTM(4,input_shape=(1,look_back)))
model.add(Dense(1))

model.compile(loss='mean_squared_error',optimizer='adam')
model.fit(trainX,trainY,epochs=500,batch_size=32,verbose=2)

Epoch 1/500
41/41 - 3s - loss: 9.8895 - 3s/epoch - 62ms/step
Epoch 2/500
41/41 - 0s - loss: 9.1354 - 91ms/epoch - 2ms/step
Epoch 3/500
41/41 - 0s - loss: 8.4085 - 94ms/epoch - 2ms/step
Epoch 4/500
41/41 - 0s - loss: 7.6531 - 101ms/epoch - 2ms/step
Epoch 5/500
41/41 - 0s - loss: 6.8181 - 97ms/epoch - 2ms/step
Epoch 6/500
41/41 - 0s - loss: 5.8444 - 92ms/epoch - 2ms/step
Epoch 7/500
41/41 - 0s - loss: 4.7115 - 96ms/epoch - 2ms/step
Epoch 8/500
41/41 - 0s - loss: 3.5126 - 103ms/epoch - 3ms/step
Epoch 9/500
41/41 - 0s - loss: 2.4230 - 102ms/epoch - 2ms/step
Epoch 10/500
41/41 - 0s - loss: 1.5704 - 101ms/epoch - 2ms/step
Epoch 11/500
41/41 - 0s - loss: 0.9753 - 96ms/epoch - 2ms/step
Epoch 12/500
41/41 - 0s - loss: 0.5893 - 102ms/epoch - 2ms/step
Epoch 13/500
41/41 - 0s - loss: 0.3500 - 96ms/epoch - 2ms/step
Epoch 14/500
41/41 - 0s - loss: 0.2061 - 90ms/epoch - 2ms/step
Epoch 15/500
41/41 - 0s - loss: 0.1217 - 110ms/epoch - 3ms/step
Epoch 16/500
41/41 - 0s - loss: 0.0733 - 96ms/epoch - 2ms/s

In [21]:
#Make predictions
trainPredict=model.predict(trainX)
testPredict=model.predict(testX)

#Invert predictions
# expm1 is exponential
trainPredict=np.expm1(trainPredict)
trainY=np.expm1(trainY)
testPredict=np.expm1(testPredict)
testY=np.expm1(testY)

#Calculate root mean squared error

trainScore=math.sqrt(mean_squared_error(trainY,trainPredict[:,0]))
print('Train Score: %.2f RMSE' %(trainScore))
testScore=math.sqrt(mean_squared_error(testY,testPredict[:,0]))
print('Test Score: %.2f RMSE' %(testScore))

Train Score: 2.36 RMSE
Test Score: 3.15 RMSE


In [22]:
# Test score should always > train score

In [23]:
test_series=pd.Series(testY)

#State the model performance

if testScore< test_series.std():
  print('\n[ Model performance is Good enough ]')
  print('\nRMSE of test prediction < Standard deviation of test dataset')
  print('%.2f' % (testScore),'<','%.2f' %(test_series.std()))
else:
    print('\n[ Model performance is Good enough ]')
    print('\nRMSE of test prediction < Standard deviation of test dataset')
    print('%.2f' % (testScore),'>','%.2f' %(test_series.std()))



[ Model performance is Good enough ]

RMSE of test prediction < Standard deviation of test dataset
3.15 < 4.41
